# -*- coding: utf-8 -*-
"""Book LLM Data Cleaning(merged File)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWD9uDdBuHPfqHsmIgh8WR5a9kPZ3rf-
"""

import pandas as pd

df=pd.read_csv('/content/merge-csv.com__67778c7c92a9f.csv')

df

df.isnull().sum()

#removed the unamed coloumns

df = df.loc[:, ~df.columns.str.contains('Unnamed')]
df

df['Title'] = df['Title'].str.strip().fillna("Untitled")

df['Authors'] = df['Authors'].fillna("Unknown Author")

df['Publisher'] = df['Publisher'].fillna("Unknown Publisher")

df['Published Date'] = df['Published Date'].fillna("Unknown Date")

df['Description'] = df['Description'].fillna("No Description Available")

df['Categories'] = df['Categories'].fillna("Uncategorized")

df.isnull().sum()

df.dtypes

import re
df['Description'] = df['Description'].apply(lambda x: re.sub(r'<.*?>', '', x))

df.to_csv('cleaned_dataset.csv', index=False)

# If you want to download the file to your local machine:
from google.colab import files
files.download('cleaned_dataset.csv')