# -*- coding: utf-8 -*-
"""Book LLM Data Cleaning(merged File)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWD9uDdBuHPfqHsmIgh8WR5a9kPZ3rf-
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/Book LLM Dataset/merge-csv.com__67778c7c92a9f.csv')

df

df.isnull().sum()

#removed the unamed coloumns

df = df.loc[:, ~df.columns.str.contains('Unnamed')]
df

df['Title'] = df['Title'].str.strip().fillna("Untitled")

df['Authors'] = df['Authors'].fillna("Unknown Author")

df['Publisher'] = df['Publisher'].fillna("Unknown Publisher")

df['Published Date'] = df['Published Date'].fillna("Unknown Date")

df['Description'] = df['Description'].fillna("No Description Available")

df['Categories'] = df['Categories'].fillna("Uncategorized")

df['Ratings Count	'] = df['Ratings Count'].fillna(0)

df['Average Rating'] = pd.to_numeric(df['Average Rating'], errors='coerce')

df['Average Rating'] = df['Average Rating'].fillna(df['Average Rating'].mean())

df['Language'] = df['Language'].fillna('en')

df['Page Count'] = df['Page Count'].fillna(0)  # Fill with 0 for Page Count

import re
df['Description'] = df['Description'].apply(lambda x: re.sub(r'<.*?>', '', x))

df.isnull().sum()

df.dtypes

df.duplicated().sum()

df.shape #Before Duplicates

df.drop_duplicates(inplace=True) #Droping Duplicates from dataset

df.shape #After Duplicates

df.head()

df.to_csv('cleaned_dataset.csv', index=False)

# If you want to download the file to your local machine:
from google.colab import files
files.download('cleaned_dataset.csv')

