# -*- coding: utf-8 -*-
"""4th Sem Project(Data Cleaning)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNSuJqOaCvx83dy5Yki7KAYmzxJXndbo
"""

import pandas as pd
df=pd.read_csv("books_dataset.csv")

df

df.head()

df.shape

df.isnull().sum()

df['Title'] = df['Title'].str.strip().fillna("Untitled")

df['Authors'] = df['Authors'].fillna("Unknown Author")

df['Publisher'] = df['Publisher'].fillna("Unknown Publisher")

df['Published Date'] = df['Published Date'].fillna("Unknown Date")

df['Description'] = df['Description'].fillna("No Description Available")

df['Categories'] = df['Categories'].fillna("Uncategorized")

average_rating_mean = df['Average Rating'].mean()
df['Average Rating'] = df['Average Rating'].fillna(average_rating_mean)

df.isnull().sum()

df['Average Rating']

import seaborn as sns
sns.boxplot(df['Average Rating'])

sns.boxplot(df['Page Count'])

# Capping Page Count at the 99th percentile
page_count_threshold = df['Page Count'].quantile(0.99)
df['Page Count'] = df['Page Count'].clip(upper=page_count_threshold)

# Clipping Average Rating between 0 and 5
df['Average Rating'] = df['Average Rating'].clip(lower=0, upper=5)

sns.boxplot(df['Page Count'])

sns.boxplot(df['Average Rating'])

import re
df['Description'] = df['Description'].apply(lambda x: re.sub(r'<.*?>', '', x))  # Removed HTML tags

